### ISSUE TITLE
Heads-up for Satellite 6.4 to 6.5 update (Error 500 when querying virt-who hosts - undefined method `split' for nil:NilClass)

### ISSUE THREAD

**Issue by kallies** [evgeni/katello-attach-subscription#73]
`katello-attach-subscription` wasn't working properly after we updated Satellite from 6.4 to 6.5. Running `katello-attach-subscription` with the `--verbose` parameter revealed, that some virt-who hosts are returning Error 500. This was reproducible in UI, API and hammer:

```
hammer host info --name virt-who-node.fqdn-1
{
  "error": {"message":"undefined method `split' for nil:NilClass"}
}
```

There is a [bugzilla](https://bugzilla.redhat.com/show_bug.cgi?id=1736809) and a [solution article](https://access.redhat.com/solutions/4275261) about this issue.

Another way is to add an additional interface, set to primary, managed and remove the old one - which is a bit annoying if there are a lot of hosts.
